soqlDemo4.accDynamicSOQL1('name');
system.debug('-----');
SoqlDemo4.accDynamicSOQL1('name, website, phone, shippingcity, active__c');


//SoqlDemo3.accContactQuery();

//SoqlDemo2.accountContactSOQL();

//SoqlDemo2.childToParent2();

//SoqlDemo.accountSOQL1();

//SoqlDemo.accountSOQLOneR();

// SoqlDemo.projectSoqlFilter('New');
// system.debug('---');
// SoqlDemo.projectSoqlFilter('In-progress');