PrimitiveDataTypeDemo2 dateExamp = new PrimitiveDataTypeDemo2 ();
dateExamp.printNewDateTime();
dateExamp.printNewTime(); 
dateExamp.printNewDate();



/* datetime dt5 = datetime.newInstance(0);
system.debug('dt 5 is ' + dt5); //1970-01-01 midnight

long longTime = 2354878745000l; //milliseconds from 1970 Jan 1 midnight
datetime dt55 = datetime.newInstance(longtime);
system.debug('dt 55 is ' + dt55); */