public class ArthimaticCalculations {
    public Integer addition(integer x,integer y) {
        Integer z = x + y;
        return z;
    }
    public Integer subtraction(integer x,integer y) {
        Integer z = x - y;
        return z;
    }
    public Integer multiplication(integer w,integer x,integer y) {
        Integer z = w*x*y;
        return z;
    }
    public String concatStrings(String a,String b) {
        String z = a + ' & ' + b;
        return z;
    }
}